server: 
  port: 9004
spring: 
  application:  
    name: tensquare-tag #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://132.232.104.247:3306/tensquare_label?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: '!QAZ2wsx'
  jpa: 
    database: MySQL
    show-sql: true
# eureka
eureka:
  client:
    service-url:
      defaultZone: http://47.98.232.143:6868/eureka/
  instance: # 开启ip注册，不开启，则使用服务名称注册
    prefer-ip-address: true
    hostname: 140.143.237.191
    ip-address: 140.143.237.191
logging:
  level:
    root: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %clr(%-5level) %logger{50}[%L] -%msg%n"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %clr(%-5level) %logger{50}[%L] -%msg%n"
  config: classpath:logback-production.xml
