server:
  port: 9010
spring:
  application:
    name: tensquare-manager #指定服务名
eureka:
  client:
    service-url:
      defaultZone: http://47.98.232.143:6868/eureka/
  instance:
    prefer-ip-address: true
# 配置网关路由
zuul:
  routes:
    tensquare-blog: # 文章, 这个是标示，需要唯一
      path: /article/**  # 配置请求的URL规则, 访问的前面都要加上 /route-key/ + /aritlce/1
      serviceId: tensquare-blog # 指定eureka中注册的服务id
    tensquare-category:
      path: /category/**
      serviceId: tensquare-category
    tensquare-tag:
      path: /tag/**
      serviceId: tensquare-tag
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
ribbon: # 配置ribbon
  ReadTimeout: 6000
  ConnectTimeout: 6000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1