server: 
  port: 9003
spring: 
  application:  
    name: tensquare-category #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.60.133:13306/tensquare_category?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: '&UJM8ik,' # 特殊符号的密码需要使用单引号包主
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 132.232.104.247
    password: tensquare!
    username: tensquare
# 日志配置
logging:
  level:
    root: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %clr(%-5level) %logger{50}[%L] -%msg%n"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %clr(%-5level) %logger{50}[%L] -%msg%n"
  config: classpath:logback-production.xml
# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://47.98.232.143:6868/eureka/
  instance: # 开启ip注册，不开启，则使用服务名称注册
    prefer-ip-address: true
    hostname: 106.14.60.133 # 注册到eurek的服务器ip，当前部署的服务器ip
    ip-address: 106.14.60.133
