server:
  port: 9001
spring:
  application:
    name: tensquare-user # 指定服务名称
  datasource:
    # url: jdbc:mysql://132.232.104.247:3306/tensquare_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    # 不显式设置字符集，集成服务器配置，服务器的mysql已经设置为utf8mb4
    url: jdbc:mysql://106.14.60.133:13306/tensquare_user?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: '&UJM8ik,'
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
  rabbitmq:
    host: 132.232.104.247
    password: tensquare!
    username: tensquare
  redis:
    host: 132.232.104.247
    port: 16379
    password: tensquare123 # 默认为空
    database: 0 # 默认也是使用 database=0
logging:
  level:
    root: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %clr(%-5level) %logger{50}[%L] -%msg%n"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %clr(%-5level) %logger{50}[%L] -%msg%n"
  config: classpath:logback-production.xml
# eureka
eureka:
  client:
    service-url:
      defaultZone: http://47.98.232.143:6868/eureka/
  instance: # 开启ip注册，不开启，则使用服务名称注册
    prefer-ip-address: true
    instance-id: blog-user  # 使用服务名注册到eureka，在eureka控制台限制的名称
# 配置feign的熔断器 hystrix
feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000
ribbon: # 配置ribbon
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 1

# 其他配置
user:
  comment:
    default:
      nickName: Developer
      avatarUrl: http://u.thsi.cn/imgsrc/sns/3ba262255b32a428a3e0b44cce35d3ee_259_346.jpg
