server:
  port: 9011
spring:
  application:
    name: tensquare-web #指定服务名
eureka:
  client:
    service-url:
      defaultZone: http://47.98.232.143:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:  #配置前端服务网关规则
  routes:
    tensquare-blog: # 文章, 这个是标示，需要唯一
      path: /article/**  # 配置请求的URL规则, 访问的前面都要加上 /route-key/ + /aritlce/1
      serviceId: tensquare-blog # 指定eureka中注册的服务id
    tensquare-category:
      path: /category/**
      serviceId: tensquare-category
    tensquare-tag:
      path: /tag/**
      serviceId: tensquare-tag
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user
    tensquare-comment:
      path: /comment/**
      serviceId: tensquare-comment
  host:
    connect-timeout-millis: 60000  # 网关的超时时间如果少于微服务的超时，则微服务的降级还没有发生，有可能网关就已经超时直接熔断了，所以网关的超时时间要大于微服务的调用超时时间*重试次数+降级调用其他服务的时间
    socket-timeout-millis: 60000
ribbon: # 配置ribbon
  ReadTimeout: 6000  #毫秒    连接超时时间
  ConnectTimeout: 6000  #毫秒    连接超时时间
  OkToRetryOnAllOperations: true  # 是否对所有操作都进行重试，对于post等非幂等性操作来说，做好幂等性接口
  MaxAutoRetries: 1  # 对当前实例的最大重试次数
  MaxAutoRetriesNextServer: 1  # 切换实例的最大重试次数(如果还失败就切换下，在切换下一个实例前，会再次重试一轮
# Ribbon超时重试次数（总的请求次数）：（MaxAutoRetries+1）*（MaxAutoRetriesNextServer+1）
# 如果Ribbon没有配置重试时间和次数，默认1S超时，默认重试1次。