server: 
  port: 9002
spring: 
  application:  
    name: tensquare-blog #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://132.232.104.247:3306/tensquare_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
  #rabbitmq
  rabbitmq:
    host: 132.232.104.247
  redis:
    host: 132.232.104.247
    port: 6379
    password: admin # 默认为空
    database: 0 # 默认也是使用 database=0
  # console 输出彩色日志
  output:
    ansi:
      enabled: always
# eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance: # 开启ip注册，不开启，则使用服务名称注册
    prefer-ip-address: true
# 配置feign的熔断器 hystrix
feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 10000
#  ribbon:
#    ReadTimeout: 3000
#    ConnectTimeout: 5000
#    MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
#    MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
#    OkToRetryOnAllOperations: false  #是否所有操作都重试
# 配置feign的链接超时时间，feign底层用的是ribbon，feign调用分为2层，一层是ribbon,一层是hystrix
