server: 
  port: 9005
spring:
  application:
    name: tensquare-comment #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.60.133:13306/tensquare_comment?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: '&UJM8ik,' # 特殊符号的密码需要使用单引号包主
  jpa:
    database: MySQL
    show-sql: true
  #rabbitmq
  rabbitmq:
    host: 132.232.104.247
    password: tensquare!
    username: tensquare
  #redis
  redis:
    host: 132.232.104.247
    port: 16379
    password: tensquare123 # 默认为空
    database: 0 # 默认也是使用 database=0
# eureka
eureka:
  client:
    service-url:
      defaultZone: http://47.98.232.143:6868/eureka/
  instance: # 开启ip注册，不开启，则使用服务名称注册
    prefer-ip-address: true
    hostname: 106.14.60.133
    ip-address: 106.14.60.133
# 日志配置
logging:
  level:
    root: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %clr(%-5level) %logger{50}[%L] -%msg%n"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %clr(%-5level) %logger{50}[%L] -%msg%n"
  config: classpath:logback-production.xml
# 配置feign的熔断器 hystrix
feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000
ribbon: # 配置ribbon
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 1

# 其他配置
comment:
  user:
    default:
      userId: 00000000000000000001